=== lecodesource/Projet_xml/joueur.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT can (equipe+)>
<!ELEMENT equipe (nom, acronyme, pays, annee_creation, joueurs)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT acronyme (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT annee_creation (#PCDATA)>
<!ELEMENT joueurs (joueur+)>
<!ELEMENT joueur (#PCDATA)>
<!ATTLIST joueur
          annee_signature CDATA #REQUIRED>

=== lecodesource/Projet_xml/joueur.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE can SYSTEM "joueur.dtd">
<can>
    <equipe>
        <nom>Black Star</nom>
        <acronyme>BSG</acronyme>
        <pays>Ghana</pays>
        <annee_creation>1957</annee_creation>
        <joueurs>
            <joueur  annee_signature="2010" >Asamoah Gyan</joueur>
            <joueur  annee_signature="2012" >Andre Ayew</joueur>
            
        </joueurs>
    </equipe>

    <equipe>
        <nom>Éperviers</nom>
        <acronyme>ETG</acronyme>
        <pays>Togo</pays>
        <annee_creation>1960</annee_creation>
        <joueurs>
            <joueur  annee_signature="2005" >Emmanuel Adebayor</joueur>
            <joueur  annee_signature="2014" >Floyd Ayité</joueur>
            
        </joueurs>
    </equipe>
</can>
