=== lecodesource/Projet_xml/livre.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="wxcv">
  <xs:element name="livre">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titre" type="xs:string"/>
        <xs:element name="auteur" type="AuteurType" minOccurs="1" maxOccurs="2"/>
        <xs:choice>
          <xs:element name="presentation" type="xs:string"/>
          <xs:element name="resume" type="xs:string"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="isbn" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="AuteurType">
    <xs:sequence>
      <xs:element name="nom" type="xs:string"/>
      <xs:element name="prenom" type="xs:string"></xs:element>
    </xs:sequence>
    <xs:attribute name="idAuteur" type="xs:integer" use="required"></xs:attribute>
  </xs:complexType>
</xs:schema>

=== lecodesource/Projet_xml/livre.xml
<?xml version="1.0" encoding="UTF-8"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="livre.xsd" isbn="978-2-7177-2113-4">
  <titre>XSD pour les nuls</titre>
  <auteur idAuteur="1">
    <nom>Dupond</nom>
    <prenom>Jean</prenom>
  </auteur>
  <auteur idAuteur="2">
    <nom>Dupont</nom>
    <prenom>Fred</prenom>
  </auteur>
  
  <presentation>Ce livre est une introduction au sch√©ma XSD</presentation>
  
</livre>
